name: First Workflow  #Workflow´s name
on: workflow_dispatch #Worflow´s trigger
jobs:
  first-job:    #Job´s name
    runs-on: ubuntu-latest
    steps: 
      - name:  Print greeting    # step´s name
        run: echo "Hello World"  # step´s command
      - name: Print Goodbye      # step´s name
        run: echo "Done - bye"   # step´s command
      - name: Mutiple Commands   # running multiple commands at once
        run: |
          echo "Command 1"
          echo "Command 2"
    

